#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#define PATH_MAX 4096

#define abort(cond, msg)                                                       \
  do {                                                                         \
    if (cond) {                                                                \
      fprintf(stderr, msg);                                                    \
      exit(EXIT_FAILURE);                                                      \
    }                                                                          \
  } while (0)

typedef uint64_t u64;
typedef uint32_t u32;
typedef int64_t i64;
typedef int32_t i32;

i64 powi(i64 b, u32 e) {
  i64 r = 1;
  while (e) r *= b, e--;
  return r;
}

u64 absi(i64 a) { return (a < 0) ? -a : a; }

typedef struct {
  u64 max, n;
  void *ptr;
} Array_t, *Array;

void arr_init_(Array arr, u64 max, u64 us) {
  arr->max = max, arr->n = 0, arr->ptr = calloc(max, us);
}
#define arr_init(T, arr, max) arr_init_(arr, max, sizeof(T))

void arr_cat_(Array arr, const void *ptr, u64 n, u64 us) {
  if (arr->max < (arr->n + n)) arr->max += arr->max / 2 + 1;
  if (arr->max < (arr->n + n)) arr->max = arr->n + n;
  arr->ptr = realloc(arr->ptr, arr->max * us);
  memcpy((char *)arr->ptr + arr->n * us, ptr, n * us);
  arr->n += n;
}
#define arr_cat(T, arr, ptr, n) arr_cat_(arr, ptr, n, sizeof(T))

void arr_free(Array arr) { free(arr->ptr), arr->n = 0, arr->max = 0; }

u64 find_moves(const char *str) {
  char *wrk = calloc(strlen(str), sizeof(char));

  sscanf(str, "[%[.#]s] %*s", wrk);
  u32 nl = strlen(wrk);

  /* start state and final state */
  u64 ss = 0, fs = 0;
  for (u32 i = 0; i < nl; i++) fs += powi(2, i) * (wrk[i] == '#');

  u64 size = powi(2, nl);
  /* convert each button to a bitmask */
  u64 *buttons = calloc(size, sizeof(u64));
  u64 off = nl + 3, nb = 0;
  while (str[off] != '{') {
    sscanf(str + off, "(%[0123456789,]s)", wrk), off += strlen(wrk) + 3;
    char *tok = strtok(wrk, ",");
    while (tok) buttons[nb] += powi(2, atoi(tok)), tok = strtok(NULL, ",");
    nb++;
  }

  /* add the start state to the frontier */
  u64 *front = calloc(2 * size, sizeof(u64)), *tmp;
  u64 *front0 = front, *front1 = front0 + size;
  front0[0] = ss;

  /* Keep adding nodes until we find the final state. New states are
   * generated by applying the buttons (bitmask) to each of the existing
   * states in the queue.*/
  u64 nf0 = 1, nf1 = 0, d = 0, nm = UINT64_MAX;
  u32 *visited = calloc(size, sizeof(u32));
  while (1) {
    for (u64 i = 0; i < nf0; i++) {
      u64 v = front0[i];
      for (u64 b = 0; b < nb; b++) {
        u64 vn = v ^ buttons[b], dn = d + 1;
        if (vn == fs) {
          nm = dn;
          goto exit_success;
        }
        if (!visited[vn]) visited[vn] = 1, front1[nf1++] = vn;
      }
    }
    d++, nf0 = nf1, nf1 = 0;
    tmp = front0, front0 = front1, front1 = tmp;
  }

exit_success:
  free(front), free(visited), free(buttons), free(wrk);

  return nm;
}

u64 solve(const char *fname) {
  FILE *fp = fopen(fname, "r");
  abort(!fp, "Unable to open input file!");

  char line[BUFSIZ];
  u64 A = 0;
  while (fgets(line, BUFSIZ, fp)) A += find_moves(line);
  fclose(fp);

  return A;
}

int main(int argc, char *argv[]) {
  char fname[PATH_MAX];
  strncpy(fname, argv[0], PATH_MAX);
  fname[strlen(fname) - 1] = '\0';

  char *ext = ((argc == 2) ? atoi(argv[1]) : 0) ? ".ex" : ".in";
  printf("%lld\n", solve(strncat(fname, ext, 3)));

  return 0;
}
